# Purpose: Run one or more secret scanners against the entire repo.

name: Run Secret Scan

on:
  push:
  workflow_dispatch:

jobs:
  gitleaks:
    name: Gitleaks
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4
      - name: Scan with Gitleaks
        uses: gitleaks/gitleaks-action@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  truffle:
    name: TruffleHog
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4
      - name: Scan with TruffleHog
        uses: trufflesecurity/trufflehog@main
        with:
          extra_args: --no-verification
